title: Mesearcher
content: []
github: true
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.1509275
  brandStrength: 0.875
  lightness: 1
  brandColors:
    - '#000400'
    - '#fefff9'
    - '#936e2a'
    - '#5a79b2'
    - '#dbbb56'
  rhythmicContrast: 1
navigation:
  - name: 'Uh, test'
    id: 2d7877c6-3c80-4b11-a58c-4454faf65e64
    type: content
  - name: Coop & Audge
    id: db5620ec-1447-4121-a8f2-756c6d1a9db4
    type: content
cta:
  bucket: null
  version: null
  domain: null
name: mesearcher
author:
  name: Bob Spunt
  email: bobspunt@gmail.com
  url: bobspunt.com
favicon: null
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
typography_spectrum: 0.15915
layout_spectrum: 1
