name: mesearcher
favicon: null
layout_spectrum: 0.34031611145474017
typography_spectrum: 0.720230603357777
title: Mesearcher
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8423755408730358
  lightness: 0.9750964036211371
  saturation: 0.9673713869415224
  rhythmicContrast: 0.795200658030808
purpose: []
