name: mesearcher
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15915
title: Mesearcher
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000400'
    - '#fefff9'
    - '#936e2a'
    - '#5a79b2'
    - '#dbbb56'
  brandStrength: 0.875
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
